baseURL: /
theme: hugo-apero
languageCode: en
title: My personal website
author: Francisco d'Albertas
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
#    - blog
    - project
    - publication
    - talk
    - talks

  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Sao Paulo
  orgName: Francisco d'Albertas
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/franciscodalbertas
#    - icon: publons
#      icon_pack: fab
#      url: https://www.facebook.com/hashtag/ap%C3%A9ro
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/franciscodalbertas/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/FdAlbertas
#    - icon: impactstory
#      icon_pack: ai
#      url: https://impactstory.org/u/0000-0002-8082-1890
    - icon: orcid
      icon_pack: ai
      url: https://impactstory.org/u/0000-0002-8082-18900000-0003-1684-0277
#    - icon: rss
#      icon_pack: fas
#      url: /blog/index.xml
    - icon: "google-scholar" # icon name without the 'fa-'
      icon_pack: ai
      url: https://scholar.google.com/citations?user=IcrbIzEAAAAJ&hl=pt-BR
    - icon: "cv" # icon name without the 'fa-'
      icon_pack: ai
      url:  "/docs/mycv.pdf
  #https://drive.google.com/file/d/1MUD_5ISH-UnNDGHg75frxnW629CcH32b/view?usp=sharing
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: apreshill/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
# Permalinks
permalinks:
  publication = "/talk/:filename/"
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
#    - name: Contributors
#      title: Contributors
#      url: /contributors/
#      weight: 3
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
#    - name: Blog
#      title: Blog
#      url: /blog/
#      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 2
# - name: Publication
#   title: My publication
#   url: /publication/
#   weight: 4
    - name: Publication
      title: Talks
      url: /talk/
      weight: 3
    - name: Talk
      title: Talks
      url: /talks/
      weight: 3
#    - name: Publication
#      title: Publication
#      url: /publication/
#      weight: 5
#    - name: Elements
#      title: Element Page
#      url: /elements/
#      weight: 4
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes


#############################################################################
## OBS
#############################################################################

# tips: https://hugo-apero-docs.netlify.app/start/section-config/

# run site: blogdown::serve_site()

# https://www.apreshill.com/blog/2020-12-new-year-new-blogdown/

# cant make publications work. crap

#############################################################################

